### ISSUE TITLE
Error -2202 LabVIEW: (Hex 0xFFFFF766) The specified name does not exist.

### ISSUE THREAD

**Issue by AndreasStark** [ni/niveristand-custom-device-wizard#20]
This is just to relay bug 1042483 (NI internal) - VS Inline-Async Custom Device template introduces a race-condition. It can be caused by NI VeriStand custom devices using the inline-async template. A temporary workaround is increasing the timout in C:\Program Files (x86)\National Instruments\LabVIEW 20xx\vi.lib\NI\NIVS Inline Async API\_VS Inline Async API\VS Inline Async API\Methods\Async.Engine.Initialize.vi to something larger than 5000ms (e.g. 15000ms) and then rebuilding the custom device.

![image](https://user-images.githubusercontent.com/10030356/85699077-81ccd800-b6db-11ea-9edc-1d9e47131b54.png)

Hope this saves someone else from countless hours of debugging.

**Comment by Tonza0511** [comment]
Posting this in case anyone else comes across this.

I also experienced this issue when using the inline-async template, but the above did not fix the issue.

I encountered error -2202 when I deployed more than one instance of the custom device in the System Definition File at the same time. This ended up being because I wrapped the Async.Processes.WaitonStart.vi as part of an initialization subVI but forgot to make that subVI use preallocated clone reentrant execution. Marking it to that execution option resolved the issue.

So if you run into this issue and the above solution does not fix things, make sure you check your VI Execution settings.
