### ISSUE TITLE
Custom Device Wizard package should have a VeriStand Custom Device Development Tools as dependent package

### ISSUE THREAD

**Issue by PaoloPereira** [ni/niveristand-custom-device-wizard#43]
**Is your feature request related to a problem? Please describe.**
If you only install the Custom Device Wizard from the release package, the Wizard will be placed in the Template project of LabVIEW but the generation will take arround 5 min and will fail at the end with error 7 on "Copy Template Files.vi"

**Describe the solution you'd like**
Make this package part of the dependencies so the user don't need to install it manually

**Describe alternatives you've considered**
Make the explanation a bit more clear of what dependencies need to be installed

**Additional context**

**Comment by buckd** [comment]
Creating a dependent package does not eliminate the need to manually install the dependent package because there is not a feed containing all the required packages, but #50 will prevent installation of the wizard package if the other package is not installed and the [release page](https://github.com/ni/niveristand-custom-device-wizard/releases/latest) has been updated to include prerequisite installers like the `README` does.
